# Generated by Django 5.1.3 on 2024-12-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_diabetesprediction_diabetes_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesprediction',
            name='DiabetesPedigreeFunction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diabetesprediction',
            name='insulin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='diabetesprediction',
            name='diabetes_prediction',
            field=models.BinaryField(blank=True),
        ),
    ]
