# Generated by Django 5.1.3 on 2024-12-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_diabetesprediction_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetesprediction',
            name='Age',
        ),
        migrations.AddField(
            model_name='diabetesprediction',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
